################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32F4xx_HAL_Driver/Src \
LCD \
LVGL_Lib/examples/anim \
LVGL_Lib/examples/assets \
LVGL_Lib/examples/assets/emoji \
LVGL_Lib/examples/event \
LVGL_Lib/examples/get_started \
LVGL_Lib/examples/layouts/flex \
LVGL_Lib/examples/layouts/grid \
LVGL_Lib/examples/libs/barcode \
LVGL_Lib/examples/libs/bmp \
LVGL_Lib/examples/libs/ffmpeg \
LVGL_Lib/examples/libs/freetype \
LVGL_Lib/examples/libs/gif \
LVGL_Lib/examples/libs/libjpeg_turbo \
LVGL_Lib/examples/libs/libpng \
LVGL_Lib/examples/libs/lodepng \
LVGL_Lib/examples/libs/qrcode \
LVGL_Lib/examples/libs/rlottie \
LVGL_Lib/examples/libs/tiny_ttf \
LVGL_Lib/examples/libs/tjpgd \
LVGL_Lib/examples/others/file_explorer \
LVGL_Lib/examples/others/fragment \
LVGL_Lib/examples/others/gridnav \
LVGL_Lib/examples/others/ime \
LVGL_Lib/examples/others/imgfont \
LVGL_Lib/examples/others/monkey \
LVGL_Lib/examples/others/observer \
LVGL_Lib/examples/others/snapshot \
LVGL_Lib/examples/porting \
LVGL_Lib/examples/scroll \
LVGL_Lib/examples/styles \
LVGL_Lib/examples/widgets/animimg \
LVGL_Lib/examples/widgets/arc \
LVGL_Lib/examples/widgets/bar \
LVGL_Lib/examples/widgets/button \
LVGL_Lib/examples/widgets/buttonmatrix \
LVGL_Lib/examples/widgets/calendar \
LVGL_Lib/examples/widgets/canvas \
LVGL_Lib/examples/widgets/chart \
LVGL_Lib/examples/widgets/checkbox \
LVGL_Lib/examples/widgets/dropdown \
LVGL_Lib/examples/widgets/image \
LVGL_Lib/examples/widgets/imagebutton \
LVGL_Lib/examples/widgets/keyboard \
LVGL_Lib/examples/widgets/label \
LVGL_Lib/examples/widgets/led \
LVGL_Lib/examples/widgets/line \
LVGL_Lib/examples/widgets/list \
LVGL_Lib/examples/widgets/menu \
LVGL_Lib/examples/widgets/msgbox \
LVGL_Lib/examples/widgets/obj \
LVGL_Lib/examples/widgets/roller \
LVGL_Lib/examples/widgets/scale \
LVGL_Lib/examples/widgets/slider \
LVGL_Lib/examples/widgets/span \
LVGL_Lib/examples/widgets/spinbox \
LVGL_Lib/examples/widgets/spinner \
LVGL_Lib/examples/widgets/switch \
LVGL_Lib/examples/widgets/table \
LVGL_Lib/examples/widgets/tabview \
LVGL_Lib/examples/widgets/textarea \
LVGL_Lib/examples/widgets/tileview \
LVGL_Lib/examples/widgets/win \
LVGL_Lib/src/core \
LVGL_Lib/src/display \
LVGL_Lib/src/draw \
LVGL_Lib/src/draw/nxp/pxp \
LVGL_Lib/src/draw/nxp/vglite \
LVGL_Lib/src/draw/renesas/dave2d \
LVGL_Lib/src/draw/sdl \
LVGL_Lib/src/draw/sw/blend/helium \
LVGL_Lib/src/draw/sw/blend \
LVGL_Lib/src/draw/sw/blend/neon \
LVGL_Lib/src/draw/sw \
LVGL_Lib/src/draw/vg_lite \
LVGL_Lib/src/drivers/display/drm \
LVGL_Lib/src/drivers/display/fb \
LVGL_Lib/src/drivers/display/ili9341 \
LVGL_Lib/src/drivers/display/lcd \
LVGL_Lib/src/drivers/display/st7735 \
LVGL_Lib/src/drivers/display/st7789 \
LVGL_Lib/src/drivers/display/st7796 \
LVGL_Lib/src/drivers/evdev \
LVGL_Lib/src/drivers/libinput \
LVGL_Lib/src/drivers/nuttx \
LVGL_Lib/src/drivers/sdl \
LVGL_Lib/src/drivers/windows \
LVGL_Lib/src/drivers/x11 \
LVGL_Lib/src/font \
LVGL_Lib/src/indev \
LVGL_Lib/src/layouts/flex \
LVGL_Lib/src/layouts/grid \
LVGL_Lib/src/layouts \
LVGL_Lib/src/libs/barcode \
LVGL_Lib/src/libs/bin_decoder \
LVGL_Lib/src/libs/bmp \
LVGL_Lib/src/libs/ffmpeg \
LVGL_Lib/src/libs/freetype \
LVGL_Lib/src/libs/fsdrv \
LVGL_Lib/src/libs/gif \
LVGL_Lib/src/libs/libjpeg_turbo \
LVGL_Lib/src/libs/libpng \
LVGL_Lib/src/libs/lodepng \
LVGL_Lib/src/libs/lz4 \
LVGL_Lib/src/libs/qrcode \
LVGL_Lib/src/libs/rle \
LVGL_Lib/src/libs/rlottie \
LVGL_Lib/src/libs/tiny_ttf \
LVGL_Lib/src/libs/tjpgd \
LVGL_Lib/src \
LVGL_Lib/src/misc/cache \
LVGL_Lib/src/misc \
LVGL_Lib/src/osal \
LVGL_Lib/src/others/file_explorer \
LVGL_Lib/src/others/fragment \
LVGL_Lib/src/others/gridnav \
LVGL_Lib/src/others/ime \
LVGL_Lib/src/others/imgfont \
LVGL_Lib/src/others/monkey \
LVGL_Lib/src/others/observer \
LVGL_Lib/src/others/snapshot \
LVGL_Lib/src/others/sysmon \
LVGL_Lib/src/others/vg_lite_tvg \
LVGL_Lib/src/stdlib/builtin \
LVGL_Lib/src/stdlib/clib \
LVGL_Lib/src/stdlib \
LVGL_Lib/src/stdlib/micropython \
LVGL_Lib/src/stdlib/rtthread \
LVGL_Lib/src/themes/default \
LVGL_Lib/src/themes \
LVGL_Lib/src/themes/mono \
LVGL_Lib/src/themes/simple \
LVGL_Lib/src/tick \
LVGL_Lib/src/widgets/animimage \
LVGL_Lib/src/widgets/arc \
LVGL_Lib/src/widgets/bar \
LVGL_Lib/src/widgets/button \
LVGL_Lib/src/widgets/buttonmatrix \
LVGL_Lib/src/widgets/calendar \
LVGL_Lib/src/widgets/canvas \
LVGL_Lib/src/widgets/chart \
LVGL_Lib/src/widgets/checkbox \
LVGL_Lib/src/widgets/dropdown \
LVGL_Lib/src/widgets/image \
LVGL_Lib/src/widgets/imagebutton \
LVGL_Lib/src/widgets/keyboard \
LVGL_Lib/src/widgets/label \
LVGL_Lib/src/widgets/led \
LVGL_Lib/src/widgets/line \
LVGL_Lib/src/widgets/list \
LVGL_Lib/src/widgets/menu \
LVGL_Lib/src/widgets/msgbox \
LVGL_Lib/src/widgets/objx_templ \
LVGL_Lib/src/widgets/roller \
LVGL_Lib/src/widgets/scale \
LVGL_Lib/src/widgets/slider \
LVGL_Lib/src/widgets/span \
LVGL_Lib/src/widgets/spinbox \
LVGL_Lib/src/widgets/spinner \
LVGL_Lib/src/widgets/switch \
LVGL_Lib/src/widgets/table \
LVGL_Lib/src/widgets/tabview \
LVGL_Lib/src/widgets/textarea \
LVGL_Lib/src/widgets/tileview \
LVGL_Lib/src/widgets/win \

